### ISSUE TITLE
请教代码调试问题

### ISSUE THREAD

**Issue by starjason** [doomiris/ssm2wjx#1]
autojs使用的版本是4.1.1，   
安装使用vs code 的插件，使用手机连接电脑进行调试。  
发现单个js文件，在vs code里面可以正常run，  
但是一旦多个文件，或者有引入其他文件，就无法运行了。 
请教大佬如何解决呢？

**Comment by doomiris** [comment]
vs的autojs插件是把文件上传到手机 /脚本/ 目录里的. 你要提前把你需要引用的文件也放进去啊. 如果用vs插件上传会忽略电脑上的文件夹结构的. 你检查一下代码里的引用位置是不是错了.
